# Generated by Django 6.0 on 2025-12-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VETERINARIAN', 'Veterinarian'), ('RECEPTIONIST', 'Receptionist'), ('SHOP_MANAGER', 'Shop Manager')], default='ADMIN', max_length=50),
        ),
    ]
