# Generated by Django 6.0.5 on 2026-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Shifokor (Stomatolog)'), ('RECEPTIONIST', 'Registrator'), ('ASSISTANT', 'Yordamchi')], default='ADMIN', max_length=50),
        ),
    ]
