# Generated by Django 6.0.5 on 2026-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_salary_percentage_doctorsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queue_prefix',
            field=models.CharField(blank=True, help_text='Navbat raqami uchun harf (masalan: A, K, S)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room_number',
            field=models.CharField(blank=True, help_text='Shifokor xonasi/kabinet raqami', max_length=10, null=True),
        ),
    ]
