# Generated by Django 6.0 on 2026-01-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_total_amount_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bonus_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid via bonuses', max_digits=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='cashback_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='New bonus earned from this payment', max_digits=20),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
        ),
    ]
