# Generated by Django 6.0 on 2025-12-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_visit_veterinarian_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notified_3d', models.BooleanField(default=False)),
                ('notified_2d', models.BooleanField(default=False)),
                ('notified_1d', models.BooleanField(default=False)),
                ('notified_today', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('no_show_notified_count', models.IntegerField(default=0)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='clinic.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='clinic.visit')),
            ],
        ),
    ]
