# Generated by Django 6.0 on 2025-12-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_pet_color_pet_microchip_pet_weight_alter_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
