# Generated by Django 6.0 on 2025-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_visit_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
