# Generated by Django 6.0 on 2025-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_visit_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
