# Generated by Django 6.0 on 2025-12-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_vaccineschedule_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
