# Generated by Django 6.0 on 2025-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_alter_medicalrecord_veterinarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='bonus_credited',
            field=models.BooleanField(default=False),
        ),
    ]
