# Generated by Django 6.0 on 2026-01-15 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_visit_bonus_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='timeline_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
    ]
