# Generated by Django 6.0 on 2026-01-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_medicalrecord_analysis_data_pet_timeline_uuid_and_more'),
        ('shop', '0014_consumableset_supplier_consumableitem_productbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='consumable_sets',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='shop.consumableset'),
        ),
    ]
