# Generated by Django 6.0 on 2026-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_customer_referral_code_customer_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='spins',
            field=models.IntegerField(default=0, help_text='Available spins from referrals'),
        ),
    ]
