# Generated by Django 6.0.5 on 2026-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_customer_spins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='queue_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
