# Generated by Django 6.0.5 on 2026-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_alter_visit_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='additional_conditions',
            field=models.TextField(blank=True, help_text="Qo'shimcha kasalliklar (ixtiyoriy)"),
        ),
    ]
