# Generated by Django 6.0.5 on 2026-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_announced',
            field=models.BooleanField(default=False),
        ),
    ]
