# Generated by Django 6.0 on 2025-12-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('POS', 'POS'), ('TELEGRAM_BOT', 'Telegram Bot')], default='POS', max_length=20),
        ),
    ]
