# Generated by Django 6.0 on 2025-12-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Chegirma foizi (0-100)'),
        ),
    ]
