# Generated by Django 6.0 on 2025-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_min_stock_alter_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notified_low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
