# Generated by Django 6.0 on 2025-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_payment_method_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_credited',
            field=models.BooleanField(default=False),
        ),
    ]
