# Generated by Django 6.0 on 2026-01-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_consumableset_supplier_consumableitem_productbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
