# Generated by Django 6.0 on 2026-01-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_customer_referral_code_customer_referred_by'),
        ('shop', '0015_order_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCustomer',
            fields=[
            ],
            options={
                'verbose_name': "Do'kon Mijozi",
                'verbose_name_plural': "Do'kon Mijozlari",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinic.customer',),
        ),
    ]
