# Generated by Django 6.0 on 2026-01-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprize',
            name='description',
            field=models.TextField(blank=True, help_text='What is this prize?', null=True),
        ),
        migrations.AddField(
            model_name='gameprize',
            name='instructions',
            field=models.TextField(blank=True, help_text='How to use/claim it?', null=True),
        ),
    ]
