# Generated by Django 6.0 on 2026-01-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameprize_description_gameprize_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
