# Generated by Django 6.0 on 2026-01-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_customer_referral_code_customer_referred_by'),
        ('games', '0003_gamesession_coupon_code_gamesession_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.customer'),
        ),
    ]
