# Generated by Django 6.0 on 2026-01-18 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamesession_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_referral_limit', models.IntegerField(default=5, help_text='Max referral spins per user per day')),
                ('fraud_threshold_ip', models.IntegerField(default=3, help_text='Max clean registrations from same IP (if tracking IP)')),
            ],
            options={
                'verbose_name': 'Game Settings',
                'verbose_name_plural': 'Game Settings',
            },
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
